### ISSUE TITLE
Accepting Negative numeric values in tabs

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#46]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel-->WooCommerce -->Products-->Add new products-->Booking products
Version: 2.0.0
Description: Accepting negative values in General settings(max bookings), Costs(Unit costs, base costs), People(Min. people, Max. people), Availability(max. booking per user)
![s32](https://user-images.githubusercontent.com/86114080/126130761-fb9a3788-04d4-47a9-a495-43c9bf498ef9.png)
![S33](https://user-images.githubusercontent.com/86114080/126130780-62b37cb8-bf02-4f3d-ab11-6c7fcf94407b.png)
![s34](https://user-images.githubusercontent.com/86114080/126131568-37002d35-b300-4566-b31c-59683b59b70b.png)
![s35](https://user-images.githubusercontent.com/86114080/126131575-b4e483eb-f8aa-492f-a23e-79775b02009b.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Issue is still persisting in base cost(cost tab)
![s78](https://user-images.githubusercontent.com/86114080/127432750-0eeca9bd-a664-4b00-882b-81da87e0074c.png)

**Comment by vivekkushwaha-cedcoss** [comment]
updated

**Comment by shrishti-mwb** [comment]
Done
