### ISSUE TITLE
There should be increase/decrease dropdown in services

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#49]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel-->Products-->Booking services-->Add new services-->check 'if has quantity' checkbox
Version: 2.0.0
Description:
In services tab there should be dropdown to increase or decrease quantity of services.
![s37](https://user-images.githubusercontent.com/86114080/126155487-c74c8d88-ed0c-4860-847e-c2109934185f.png)
![s38](https://user-images.githubusercontent.com/86114080/126155492-24c26a59-61d1-45e4-98bb-a13ba9ecf54d.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Not fixed
![s83](https://user-images.githubusercontent.com/86114080/127437357-8ec57703-1b96-4f57-a4ed-a6ab26a472dd.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Done
